config/routes.rb
Rails.application.routes.draw do

  # use_doorkeeper
  
  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  # get 'sessions/new'
  resources :sessions, :users

  get 'static/home'
  get 'screencasts' => 'static#media'
  get 'preface' => 'static#preface'
  get 'errata' => 'static#errata'
  get 'examples' => 'static#examples'
  get 'education' => 'static#education'
  get 'foreword' => 'static#foreword'
  get 'static/share'

  mount Ckeditor::Engine => '/ckeditor'

  root 'static#home'
end

app/models/forum.rb
class Forum < ApplicationRecord
	has_many :topics, dependent: :destroy
	has_many :posts, through: :topics

	accepts_nested_attributes_for :topics
	accepts_nested_attributes_for :posts

	def most_recent_post
	  post = self.topics.last.posts.last
	  return post
	end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name, :description)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(forum) do |f| %>
  <% if forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<h1>Forums</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Forum</th>
      <th class="right">Last Post</th>
    <% if current_user && current_user.admin %>
      <th>Actions</th>
    <% end %>
    </tr>
  </thead>

  <tbody>
    <% @forums.each do |forum| %>
      <tr>
        <td>
          <h4><%= link_to (forum.name), forum_path(forum.id) %></h4>
          <small><%= pluralize(forum.topics.count, "topic") %></small>
          <br>
          <%= forum.description %>
        </td>
        <td class="right">
          <% if forum.most_recent_post %>
            Posted on <%= forum.most_recent_post.created_at.to_time.strftime("%D at %I:%M %p") %><br>
             by <strong><%= forum.most_recent_post.user.username %></strong>
          <% else %>
            No posts yet
          <% end %>
        </td>
        <% if current_user && current_user.admin %>
          <td><%= link_to forum, class: "btn btn-sm btn-primary" do %>
                        <i class="fa fa-eye"></i> <strong>SHOW</strong>
              <% end %>
              <br>
              <%= link_to edit_forum_path(forum), class: "btn btn-sm btn-warning" do %>
                        <i class="fa fa-wrench"></i> <strong>EDIT</strong>
              <% end %>
              <br>
              <%= link_to forum, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-danger" do %>
                        <i class="fa fa-bomb"></i> <strong>DESTROY</strong>
              <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.admin %>
  <%= link_to new_forum_path, class: "btn btn-l btn-success" do %>
    <i class="fa fa-plus"></i> <strong>New Forum</strong>
  <% end %>
<% else end %>

app/views/forums/new.html.erb
<h1>New Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<h3>
  <strong>Forum Name:</strong>
  <%= @forum.name %>
</h3>

<p>
  <strong>Description:</strong>
  <%= @forum.description %>
</p>

<table class="table table-bordered table-striped">
  <tr>
    <th width="40%">Topics</th>
    <th width="5%" class="center">Posts</th>
    <th width="30%" class="right">Last Post</th>
<% if current_user && current_user.admin %>
    <th width="25%">Actions</th>
<% end %>
  </tr>
  <% @forum.topics.each do |topic| %>
    <tr>
      <td><%= link_to (topic.title), [ @forum, topic ], class: "topic-link"%>
      <td class="center"><%= topic.posts.count %></td>
      <% if topic.posts.any? %>
        <td class="right"><%= topic.posts.last.updated_at.to_time.strftime("%D at %I:%M %p") %> by <strong><%= topic.posts.last.user.username %></strong></td>
      <% else %>
        <td class="right"><em>No posts yet</em></td>
      <% end %>
      <% if current_user && current_user.admin %>
        <td><%= link_to [ @forum, topic ], class: "btn btn-xs btn-primary" do %>
              <i class="fa fa-eye"></i> <strong>SHOW</strong>
            <% end %>
            <%= link_to edit_forum_topic_path( @forum, topic ), class: "btn btn-xs btn-warning" do %>
              <i class="fa fa-wrench"></i> <strong>EDIT</strong>
            <% end %>
            <%= link_to [ @forum, topic ], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" do %>
              <i class="fa fa-bomb"></i> <strong>DESTROY</strong>
            <% end %>
      <% end %>
    </tr>
  <% end %>
</table>
<div id="centered-controls">
<!-- New Topic button -->
  <% if current_user %> 
    <%= link_to new_forum_topic_path(@forum), class: "btn btn-primary", style: "color: #FFF;" do %>
        <i class="fa fa-plus"></i> <strong>New Topic</strong>
    <% end %>
  <% end %>
  <!-- Edit Forum button -->
  <% if current_user && current_user.admin %>
  	<%= link_to edit_forum_path(@forum), class: "btn btn-warning", style: "color: #FFF;" do %>
      <i class="fa fa-edit"></i> <strong>Edit</strong>
  	<% end %>
  <% end %>
  <!-- Back button -->
  <%= link_to forums_path, class: "btn btn-dark", style: "color: #FFF;" do %>
      <i class="fa fa-backward"></i> <strong>Forums</strong>
  <% end %>
</div>