config/routes.rb
Rails.application.routes.draw do

  # use_doorkeeper
  
  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  # get 'sessions/new'
  resources :sessions, :users

  get 'static/home'
  get 'screencasts' => 'static#media'
  get 'preface' => 'static#preface'
  get 'errata' => 'static#errata'
  get 'examples' => 'static#examples'
  get 'education' => 'static#education'
  get 'foreword' => 'static#foreword'
  get 'static/share'

  mount Ckeditor::Engine => '/ckeditor'

  root 'static#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :forum
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :users, through: :posts

  accepts_nested_attributes_for :posts

  validates :title, presence: true
  # validates_associated :posts
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :get_forum
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = @forum.topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @post = Post.new
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    @topic.posts.new
  end

  # GET /topics/1/edit
  def edit
    # @topic.posts.build
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = @forum.topics.new topic_params
    @topic.last_poster_id = current_user.id
    @topic.user = current_user
    @topic.posts.first.user_id = current_user.id
    @topic.posts.first.topic = @topic

    respond_to do |format|
      if @topic.save
        # @topic.posts.create(content: posts_attributes(:content), forum_id: @forum.id, topic_id: @topic.id, user_id: current_user.id)

        format.html { redirect_to forum_topic_path(@forum, @topic), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to forum_topic_path(@forum, @topic), notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to forum_path(@forum), notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def create_post
  #   @topic = Topic.find(params[:id])
  #   @post = @topic.posts.build(params[:post])
  #   respond_to do |format|
  #     if @post.save
  #       @post = Post.new
  #       format.html { redirect_to forum_topic_path(@forum, @topic), notice: 'Your response has been posted.' }
  #       format.json { render :show, status: :ok, location: @topic }
  #     else
  #       format.html { render :show, alert: "ERROR: Post not saved!" }
  #       format.json { render json: @topic.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_forum
      @forum = Forum.find(params[:forum_id])
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:id, :title, :last_poster_id, :last_post_at, :tags, posts_attributes: [:id, :content])
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for([ @forum, topic ]) do |f| %>
  <div class="form-group">
    <% if topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

        <ul>
        <% topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_field :title, placeholder: "Title", class: "form-control title-field" %>
    </div>

    <div class="field">
      <%= f.fields_for :posts do |p| %>
          <%= p.label :content %><br>
          <%= p.cktext_area :content, class: 'ckeditor' %>
      <% end %>
    </div>

    <div class="form-group actions">   
      <%= f.submit 'Create Topic', class: "btn btn-l btn-success" %>
      <%= link_to 'Cancel', forum_path(@forum), class: "btn btn-l btn-danger" %>
    </div>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', [ @forum, @topic ] %> |
<%= link_to 'Back', forum_path(@forum) %>

app/views/topics/index.html.erb
<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Last poster</th>
      <th>Last post at</th>
      <th>Tags</th>
      <th>Forum</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.last_poster_id %></td>
        <td><%= topic.last_post_at %></td>
        <td><%= topic.tags %></td>
        <td><%= topic.forum %></td>
        <td><%= topic.user %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_forum_topic_path(@forum) %>

app/views/topics/new.html.erb
<h2>New Topic for <%= @forum.name %> Forum</h2>

<%= render 'form', topic: @topic %>

app/views/topics/show.html.erb
<div id="topicHeading">
  <h3 id="topicTitle"><span style="color: #ff54e8;">topic</span> <%= @topic.title %> <span style="color: #88f738;">&lt; <em><%= @forum.name %></em></span></h3>
  <br>
</div>

<table class="table table-bordered">
  <tr style="background: #F7F7F7;">
    <td>
      <strong>Last post by </strong>
      <em><%= @topic.posts.last.user.username %></em>
      on <%= @topic.posts.last.updated_at.to_time.strftime("%D at %I:%M %p") %>
    </td>
    <td>
      <strong>Started by:</strong>
       <em><%= @topic.posts.first.user.username %></em>
       on <%= @topic.created_at.to_time.strftime("%D at %I:%M %p") %>
    </td>
  </tr>
</table>

<% if @topic.posts.any? %>
  <% @topic.posts.each do |post| %>
    <div class="panel panel-default panel-themed">
      <div class="panel-heading">
        <%= post.created_at.to_time.strftime("%D at %I:%M %p") %> by <strong><%= post.user.username %></strong>
        <% if current_user && current_user.admin %>
          <%= button_to "Delete Post", forum_topic_post_path(@forum, @topic, post), method: :delete, id: "delete-post", data: { confirm: "Are you sure?" } %>
        <% end %>
      </div>
      <div class="panel-body"><%= sanitize post.content %></div>
    </div>
  <% end %>
<% else %>
  <br>
  <div class="jumbotron">
    <h3>Nothing to see here...</h3>
  </div>
<% end %>

<!--New Post Form -->
  <div class="panel panel-default panel-themed collapse" id="newPostForm">
      <div class="panel-heading">New Post</div>
      <% if current_user %>
          <%= render partial: "posts/form" %>
      <% end %>
  </div>  
<!-- end new post form -->

</div>
<br>
<div id="centered-controls">
  <%= link_to forum_path(@forum), class: "btn btn-dark", style: "color: #FFF;" do %>
      <i class="fa fa-backward"></i> <strong>Topics</strong>
  <% end %>
  <% if current_user %>
    <% if current_user.admin %>
      <%= link_to edit_forum_topic_path(@forum, @topic), class: "btn btn-warning", style: "color: #FFF;" do %>
        <i class="fa fa-edit"></i> <strong>Edit</strong>
          <% end %>
      <% end %>

      <!-- Link to New Post Form -->
      <%= link_to "#newPostForm", class: "btn btn-info", "data-toggle": "collapse", id: "beginNewPostButton" do %>
        <strong>Post a Response </strong><i class="fa fa-forward"></i>
      <% end %>
      <!-- end link to new post form -->
      
      <%= link_to "#newPostForm", class: "editing-buttons-hidden btn btn-danger", "data-toggle": "collapse", id: "newPostButton" do %>
        <i class="fa fa-bomb"></i><strong> Cancel</strong>
      <% end %>
      <%= link_to "", onclick: "$('#newPost').submit()", class: "editing-buttons-hidden btn btn-success", id: "newPostButton" do %>
        <i class="fa fa-check"></i><strong> Submit Post</strong>
      <% end %>
  <% else %>
    <!--<strong><%= link_to "Sign Up", new_user_path, remote: true, id: "loginLinks", data: { toggle: "modal", target: "#new_user_modal"} %>
    or
    <%= link_to "Log In", new_session_path, remote: true, id: "loginLinks", data: { toggle: "modal", target: "#new_session_modal"} %>
    to respond</strong>-->
  <% end %>
</div>
<!-- Sign Up Modal -->
<div class="modal fade" id="new_user_modal" role="dialog" aria-labelledby="sign-up-form" aria-hidden="true"></div>
<!-- Log In Modal -->
<div class="modal fade" id="new_session_modal" role="dialog" aria-labelledby="log-in-form" aria-hidden="true"></div>