config/routes.rb
Rails.application.routes.draw do

  # use_doorkeeper
  
  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  # get 'sessions/new'
  resources :sessions, :users

  get 'static/home'
  get 'screencasts' => 'static#media'
  get 'preface' => 'static#preface'
  get 'errata' => 'static#errata'
  get 'examples' => 'static#examples'
  get 'education' => 'static#education'
  get 'foreword' => 'static#foreword'
  get 'static/share'

  mount Ckeditor::Engine => '/ckeditor'

  root 'static#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_filter :block_ip_addresses

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  private

  def authorize
  	redirect_to login_url, alert: "Not Authorized" if current_user.nil?
  end

  def is_admin
    redirect_to root_path, alert: "Not authorized" if current_user.nil? or !current_user.admin?
  end

  def block_ip_addresses
    head :unauthorized if current_ip_address == "184.154.139.9"
  end

  def current_ip_address
    request.env['HTTP_X_REAL_IP'] || request.env['REMOTE_ADDR']
  end

  before_action :prepare_meta_tags, if: "request.get?"

  def prepare_meta_tags(options={})
    site_name   = "LearningRails5"
    title       = [controller_name, action_name].join(" ")
    description = "Learning Rails 5 - Available from O'Reilly Media"
    image       = options[:image] || "/assets/images/book-icon.jpg"
    current_url = request.url

    # Let's prepare a nice set of defaults
    defaults = {
      site:        site_name,
      title:       title,
      image:       image,
      description: description,
      keywords:    %w[ruby rails 5 web software development oreilly locklear learning education app],
      twitter: {
        site_name: site_name,
        site: 'http://www.learningRails5.com',
        card: 'If you’re a web developer or designer ready to learn Ruby on Rails, this unique book is the ideal way to start. All you need to get started is a little HTML experience. Each chapter includes exercises and review questions to test your understanding as you go.',
        description: description,
        image: image
      },
      og: {
        url: current_url,
        site_name: site_name,
        title: title,
        image: image,
        description: description,
        type: 'website'
      }
    }

    options.reverse_merge!(defaults)

    set_meta_tags options
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer>
	<div class="container">
		<div id="author-img">
			<%= image_tag "mark-locklear.jpg" %>
		</div>
		<div id="about-author">
			<h3>About the Author</h3>
			<p><strong>Mark Locklear</strong> is a web developer at the eXtension Initiative and has 20 years of IT experience including network administration, quality assurance, and software development. He is an Adjunct Instructor at Asheville Buncombe Technical Community College and is passionate about education and teaching students software development.</p>
			<%= link_to "Visit Mark's Homepage", "http://locklear.me/", target: "_blank" %>
			<div class="author-social">
				<%= link_to "http://www.twitter.com/marklocklear", target: "_blank" do%><i class="fa fa-twitter fa-2x"></i><% end %>
				<%= link_to "http://www.github.com/marklocklear", target: "_blank" do%><i class="fa fa-github fa-2x"></i><% end %>
				<%= link_to "https://www.linkedin.com/in/mark-locklear-3a8719", target: "_blank" do%><i class="fa fa-linkedin fa-2x"></i><% end %>
			</div>
		</div>
		<div id="book-info">
			<h3>Book Info:</h3>
			<br>
			<ul><li><strong>Languages: </strong>English, Portugese</li>
					<li><strong>Date Published: </strong>Aug. 2016 (est)</li>
					<li><strong>Paperback: </strong>400 pages</li>
					<li><strong>ISBN: </strong>978-1-4919-2619-2</li></ul>
		</div>
	</div>
</footer>

app/views/application/_heading.html.erb
<div class="heading">
	<h1>Learning Rails 5</h1>
	<p>by Mark Locklear</p>
</div>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        Menu                       
      </button>
      <%= link_to "Buy eBook", "http://shop.oreilly.com/product/0636920039822.do", class: "btn btn-dark navbar-toggle", style: "color: #FFF; background-color: #B63E97;", target: "_blank" %>
      <%= link_to "Learning Rails 5", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li> 
        <li class="<%= 'active' if current_page?(preface_path) %>"><%= link_to "Preface", preface_path %></li> 
        <li class="<%= 'active' if current_page?(errata_path) %>"><%= link_to "Errata", errata_path %></li>
        <li class="<%= 'active' if current_page?(examples_path) %>"><%= link_to "Examples", examples_path %></li>
        <li class="<%= 'active' if current_page?(screencasts_path) %>"><%= link_to "Screencasts", screencasts_path %></li>
        <li class="<%= 'active' if current_page?(forums_path) %>"><%= link_to "Forum", forums_path %></li>
        <li class="<%= 'active' if current_page?(education_path) %>"><%= link_to "Teach", education_path, {:style=>'padding: 8px 15px;'} %></li>
        <li class="share-button"><a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true" style="padding: 8px 15px;"><i class="fa fa-share-square-o"></i>Share</a>
          <%= render 'share' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="modal fade" id="share_modal" tabindex="-1" role="dialog" aria-labelledby="share_modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
<!--       <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i>Close</button>
      <h4 class="modal-title" id="myModalLabel">Spread the Word!</h4>
      </div>
      <div class="modal-body">
            <%# image_tag "loading.gif" %>
            <%# render 'facebook_modal' %>
      </div> -->
    </div>
  </div>
</div>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/application/_share.html.erb
<!-- <ul class="dropdown-menu share-menu">
  <li><a href="https://www.linkedin.com/shareArticle?mini=true&url=http%3A//learningrails5.com&title=Learning%20Rails%205%20-" class="share-link" data-toggle="modal"></a><i class="fa fa-linkedin fa-2x"></i></li>
  <li><a href="https://twitter.com/intent/tweet" data-url="http://learningrails5.com" class="share-link" data-via="learningrails5" data-toggle="modal" ><i class="fa fa-twitter fa-2x"></i></a></li>
  <li><a href="https://www.facebook.com/sharer/sharer.php?u=SHAREMESSAGE" title="Share on Facebook" target="_blank" class="btn btn-facebook"</a><i class="fa fa-facebook fa-2x"></i></li>
  <li><a href="https://plus.google.com/share?url=SHAREMESSAGE" title="Share on Google+" target="_blank" class="btn btn-googleplus"><i class="fa fa-google-plus fa-2x"></i></li>
  <li><i class="fa fa-paper-plane fa-2x"></i></li>
</ul> -->
<ul class="dropdown-menu">
	<div class="btn-group">

	  <a href="https://twitter.com/intent/tweet" data-url="http://learningrails5.com" data-via="learningrails5" data-toggle="modal" type="button" class="btn twitter"><i class="fa fa-twitter fa-2x"></i></a>

	  <a href="https://www.linkedin.com/shareArticle?mini=true&url=http%3A//learningrails5.com/&title=Learning%20Rails%205%20-%20Available%20from%20O'Reilly%20Media&summary=&source=" data-toggle="modal" target="_blank" type="button" class="btn linkedin"><i class="fa fa-linkedin fa-2x"></i></a>

	  <a href="https://plus.google.com/share?url=http%3A//www.learningrails5.com" data-toggle="modal" target="_blank" type="button" class="btn google-plus"><i class="fa fa-google-plus fa-2x"></i></a>

	  <a href="https://www.facebook.com/sharer/sharer.php?u=http%3A//www.learningrails5.com" type="button" data-toggle="modal" target="_blank" target="_top" type="button" class="btn facebook"><i class="fa fa-facebook fa-2x"></i></a>

	  <a type="button" class="btn paper-plane"><i class="fa fa-paper-plane fa-2x"></i></a>

	</div>
</ul>